stages:
  - deploy
deploy_dev-fe:
  stage: deploy
  tags:
    - zaffre
  script:
    - cp .env.dev .env
    - docker build -t myapp:dev .
    - docker run -d --name devfe -p 3002:3000 myapp:dev
  only:
    - development