stages:
  - deploy
deploy_dev-fe:
  stage: deploy
  tags:
    - zaffretech
  script:
    - cp .env.dev .env
    - sudo npm i -f
    - sudo npm run build
    - pm2 restart devfe
  only:
    - development